---
- hosts: localhost

  tasks:
    - debug: var=secret
    - debug: var=project
    - debug: var=vm
    - debug: var=vms
    - debug: var=net
    - debug: var=tmp
    - debug: var=cluster_meta
    - debug: var=job_meta
    
    - name: "install nginx"
      apt:
        name=nginx
        
    - name: "tmp write: www_install_{{ vm.host }} -> true"
      grizzly_tmp:
        write:
          key: "www_install_{{ vm.host }}"
          value: "true"

    - name: "echo: nginx install"
      grizzly_echo:
        job: "demo-app/core"
        message: "nginx install"
       
       
