---
- hosts: localhost

  tasks:
    - debug: var=secret
    - debug: var=project
    - debug: var=vm
    - debug: var=vms
    - debug: var=net
    - debug: var=tmp
    - debug: var=cluster_meta
    - debug: var=project_meta
    - debug: var=job_meta
    
    - name: "install haproxy"
      apt:
        name=haproxy
        
    - name: "echo: haproxy install"
      grizzly_echo:
        job: "demo-app/haproxy"
        message: "haproxy install"
       
